export const Action = {
  LOADING_START: "LOADING_START",
  LOADING_END: "LOADING_END",

  CSS_VARIABLES: "CSS_VARIABLES",

  METADATA: "METADATA",
  NAME: "NAME"
};

export const Mutation = {
  LOADING_START: "LOADING_START",
  LOADING_END: "LOADING_END",

  CSS_VARIABLES: "CSS_VARIABLES",

  METADATA: "METADATA",
  NAME: "NAME"
};
