import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@/assets/styles/index.scss";
import classNames from "classnames";
import Script from "next/script";

import { Header, Main, Footer } from "@/components/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const SCRIPT_CONTENT = `
// Add dark / light detection that runs before Vue.js load. Borrowed from overreacted.io
(function() {
  window.__onThemeChange = function() {};
  function setTheme(newTheme) {
    window.__theme = newTheme;
    preferredTheme = newTheme;
    document.body.setAttribute("data-theme", newTheme);
    document.documentElement.setAttribute("data-theme", newTheme);
    window.__onThemeChange(newTheme);
  }

  var preferredTheme;
  try {
    preferredTheme = localStorage.getItem("theme");
  } catch (err) {}

  window.__setPreferredTheme = function(newTheme) {
    setTheme(newTheme);
    try {
      localStorage.setItem("theme", newTheme);
    } catch (err) {}
  };

  var darkQuery = window.matchMedia("(prefers-color-scheme: dark)");
  darkQuery.addListener(function(e) {
    window.__setPreferredTheme(e.matches ? "dark" : "light");
  });

  setTheme(preferredTheme || (darkQuery.matches ? "dark" : "light"));
})();
`;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={classNames("flex flex-col min-h-screen", inter.className)}
      >
        <script
          dangerouslySetInnerHTML={{
            __html: SCRIPT_CONTENT,
          }}
        />
        <Header />
        <Main className=" flex-1">{children}</Main>
        <Footer />
      </body>
    </html>
  );
}
