name: Update Resume PDF

on:
  workflow_dispatch:

jobs:
  update-resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest resume PDF
        run: |
          mkdir -p public/assets/resources/pdf
          curl -L "https://tkhquang.dev/api/pdf?url=https://tkhquang.dev/resume" --output public/assets/resources/pdf/Quang_Trinh_Khac-Resume.pdf

      - name: Commit and push if updated
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/assets/resources/pdf/Quang_Trinh_Khac-Resume.pdf
          git diff --cached --quiet || git commit -m "chore: update resume PDF"
          git push
